### PR TITLE
[IIDM v1.6.0] Add InjectionObservability extension (#363)

### LINKED ISSUE #363: Add new extension : InjectionObservability
* **Do you want to request a *feature* or report a *bug*?**

Feature
Backport of https://github.com/powsybl/powsybl-core/pull/1788

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

### PR DESCRIPTION
**Pull request by sebalaig**
**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
Closes #363 

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

### CODE REVIEW

File: extensions/iidm/src/InjectionObservabilityXmlSerializer.cpp [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
+    writeOptionalQuality(QUALITY_Q, injectionObservability.getQualityQ(), context.getWriter());
+    writeOptionalQuality(QUALITY_V, injectionObservability.getQualityV(), context.getWriter());
+}
+
+void InjectionObservabilityXmlSerializer::writeOptionalQuality(const std::string& elementName, const stdcxx::CReference<ObservabilityQuality>& quality, xml::XmlStreamWriter& writer) const {
+    if (quality) {
+        writer.writeStartElement(getNamespacePrefix(), elementName);
+        writer.writeAttribute(STANDARD_DEVIATION, quality.get().getStandardDeviation());
+        if (quality.get().isRedundant()) {
+            writer.writeAttribute(REDUNDANT, *quality.get().isRedundant());
```
Comment (mathbagu) [inline extensions/iidm/src/InjectionObservabilityXmlSerializer.cpp:74]: From my point of view, it's not equivalent to the Java code:
```
XmlUtil.writeOptionalBoolean(REDUNDANT, quality.isRedundant(), false, writer);
```

If `quality.isRedundant()` is null, there is a NullPointerException due to the automatic conversion from `Boolean` to `boolean`. Moreover, if the value is `false`, the attribute is not serialized.

Comment (mathbagu) [reply extensions/iidm/src/InjectionObservabilityXmlSerializer.cpp:74]: I will check with powsybl-core dev team to know if we really need an `optional<bool>` there

**Comment by mathbagu** [comment]
@sebalaig I fixed few things, mainly by using default parameters to avoid to duplicate methods. Please have a look to my commit and tell me if you're OK with the changes

**Comment by sebalaig** [comment]
> @sebalaig I fixed few things, mainly by using default parameters to avoid to duplicate methods. Please have a look to my commit and tell me if you're OK with the changes

Thank you for the fixes, I approve them 👍

File: extensions/iidm/src/InjectionObservabilityXmlSerializer.cpp (hunk 1 above)
Comment (mathbagu) [reply extensions/iidm/src/InjectionObservabilityXmlSerializer.cpp:77]: https://github.com/powsybl/powsybl-core/pull/1941#pullrequestreview-854464591

File: extensions/iidm/include/powsybl/iidm/extensions/iidm/ObservabilityQuality.hpp [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+    bool isRedundant() const;
+
+    ObservabilityQuality& setRedundant(bool redundant);
+
+    ObservabilityQuality& setStandardDeviation(double standardDeviation);
+
+private:
+    double m_standardDeviation;
+
+    bool m_redundant = false;
```
Comment (mathbagu) [inline extensions/iidm/include/powsybl/iidm/extensions/iidm/ObservabilityQuality.hpp:39]: This assignment is useless since the constructor set the two fields

File: extensions/iidm/src/ObservabilityQuality.cpp [hunk 3]
```diff
@@ -0,0 +1,49 @@
+/**
+ * Copyright (c) 2021, RTE (http://www.rte-france.com)
```
Comment (mathbagu) [inline extensions/iidm/src/ObservabilityQuality.cpp:2]: Fix copyright

File: extensions/iidm/include/powsybl/iidm/extensions/iidm/InjectionObservability.hpp [hunk 4]
```diff
@@ -0,0 +1,78 @@
+/**
+ * Copyright (c) 2021, RTE (http://www.rte-france.com)
```
Comment (mathbagu) [inline extensions/iidm/include/powsybl/iidm/extensions/iidm/InjectionObservability.hpp:2]: Fix copyright date

File: include/powsybl/stdcxx/reference.hpp [hunk 5]
```diff
@@ -132,6 +138,11 @@ Reference<T> ref(const std::unique_ptr<T>& pointer) {
     return static_cast<bool>(pointer) ? Reference<T>(*pointer) : Reference<T>();
 }
 
+template <typename T, typename = typename std::enable_if<!std::is_abstract<T>::value>::type>
+Reference<T> ref(stdcxx::optional<T>& optional) {
+    return static_cast<bool>(optional) ? Reference<T>(*optional) : Reference<T>();
+}
+
```
Comment (mathbagu) [inline include/powsybl/stdcxx/reference.hpp:145]: To be reverted ?

File: include/powsybl/stdcxx/reference.hpp [hunk 6]
```diff
@@ -107,6 +108,11 @@ CReference<T> cref(const std::unique_ptr<T>& pointer) {
     return static_cast<bool>(pointer) ? CReference<T>(*pointer) : CReference<T>();
 }
 
+template <typename T, typename = typename std::enable_if<!std::is_abstract<T>::value>::type>
+CReference<T> cref(const stdcxx::optional<T>& optional) {
+    return static_cast<bool>(optional) ? CReference<T>(*optional) : CReference<T>();
+}
+
```
Comment (mathbagu) [inline include/powsybl/stdcxx/reference.hpp:115]: To be reverted?

**Review by mathbagu — APPROVED** [review]
