### PR TITLE
[IIDM v1.6.0] Make substations optional (#365)

### LINKED ISSUE #365: Make substations optional
* **Do you want to request a *feature* or report a *bug*?**

Feature
Backport of:
- https://github.com/powsybl/powsybl-core/pull/1796
- https://github.com/powsybl/powsybl-core/pull/1818
- https://github.com/powsybl/powsybl-core/pull/1865

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

### PR DESCRIPTION
**Pull request by sebalaig**
**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
Closes #365 

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

### CODE REVIEW

File: src/iidm/ThreeWindingsTransformerAdder.cpp [hunk 1]
```diff
@@ -71,14 +89,20 @@ ThreeWindingsTransformer& ThreeWindingsTransformerAdder::add() {
...
+    }
+    if (static_cast<bool>(m_substation)) {
+        return m_substation.get().getNetwork();
+    }
+    throw PowsyblException("Three windings transformer has no container");
 }
 
 Network& ThreeWindingsTransformerAdder::getNetwork() {
-    return m_substation.getNetwork();
+    return const_cast<Network&>(static_cast<const ThreeWindingsTransformerAdder*>(this)->getNetwork());
```
Comment (sebalaig) [inline src/iidm/ThreeWindingsTransformerAdder.cpp:102]: Notice: sonar is not happy with thoses hacks... But I think it is better than duplicating const methods content...

File: src/iidm/VoltageLevel.cpp [hunk 2]
```diff
@@ -245,8 +260,10 @@ void VoltageLevel::remove() {
     // Remove the topology
     removeTopology();
 
-    // Remove this voltage level from the network
-    getSubstation().remove(*this);
+    if (getSubstation()) {
```
Comment (mathbagu) [inline src/iidm/VoltageLevel.cpp:263]: It's not necessary to call the getter here? It's useful in Java to map the return of the getter and use the fluent API of the `Optional` class

File: src/iidm/VoltageLevel.cpp [hunk 3]
```diff
@@ -262,6 +279,12 @@ VoltageLevel& VoltageLevel::setLowVoltageLimit(double lowVoltageLimit) {
     return *this;
 }
 
+void VoltageLevel::setNetworkRef(Network& network) {
+    if (static_cast<bool>(m_networkRef)) {
+        m_networkRef = network;
+    }
```
Comment (mathbagu) [inline src/iidm/VoltageLevel.cpp:285]: To be discuss: I think the networkRef should be settable to null (empty reference) when the voltage is detached from the network

File: src/iidm/util/Substations.cpp [hunk 4]
```diff
@@ -41,28 +41,30 @@ void checkRemovability(const Substation& substation) {
 }
 
 void checkRemovability(const Substation& substation, const Branch& branch) {
-    const Substation& s1 = branch.getTerminal1().getVoltageLevel().getSubstation();
-    const Substation& s2 = branch.getTerminal2().getVoltageLevel().getSubstation();
-    if (!stdcxx::areSame(s1, substation) || !stdcxx::areSame(s2, substation)) {
+    const auto& s1 = branch.getTerminal1().getVoltageLevel().getSubstation();
+    const auto& s2 = branch.getTerminal2().getVoltageLevel().getSubstation();
+    if ((static_cast<bool>(s1) && !stdcxx::areSame(s1.get(), substation)) || (static_cast<bool>(s2) && !stdcxx::areSame(s2.get(), substation))) {
```
Comment (mathbagu) [inline src/iidm/util/Substations.cpp:46]: It could be interesting to extract the test `(static_cast<bool>(s1) && !stdcxx::areSame(s1.get(), substation))` in a utility function

**Review by mathbagu — COMMENTED** [review]
From my point of view, if we keep both `getSubstation` and `getNullableSubstation`, maybe the `getSubstation` should maybe throw an exception to avoid having an alias countrary at what we have in java.

File: src/iidm/VoltageLevel.cpp (hunk 2 above)
Comment (sebalaig) [reply src/iidm/VoltageLevel.cpp:263]: Agree. Fixed

File: src/iidm/util/Substations.cpp (hunk 4 above)
Comment (sebalaig) [reply src/iidm/util/Substations.cpp:46]: Agree. I added it in Substations.cpp file.
```
bool areDifferentSubstations(const stdcxx::CReference<Substation>& s1, const Substation& s2) {
    return static_cast<bool>(s1) && !stdcxx::areSame(s1.get(), s2);
}
```

I could hav added in memory.hpp, because this function is not intuitive enough IMHO : I would expect it returns true if the first parameter is invalid but it does not => to be discussed

File: include/powsybl/iidm/ThreeWindingsTransformer.hpp [hunk 5]
```diff
@@ -49,13 +49,17 @@ class ThreeWindingsTransformer : public Connectable {
...
+
     double getRatedU0() const;
 
     Side getSide(const Terminal& terminal) const;
 
-    const Substation& getSubstation() const;
+    stdcxx::CReference<Substation> getSubstation() const;
 
-    Substation& getSubstation();
+    stdcxx::Reference<Substation> getSubstation();
```
[the remark this answers is not in the document]
Comment (sebalaig) [reply include/powsybl/iidm/ThreeWindingsTransformer.hpp:62]: You're right, there is not any... I wanted to be java-like, but that's not consistent with current C++ philosophy : get throw exceptions if the object does not exist. getNullableSubstation is OK.
=> updated

File: src/iidm/VoltageLevel.cpp (hunk 3 above)
Comment (sebalaig) [reply src/iidm/VoltageLevel.cpp:291]: The bug exists in java => I posted https://github.com/powsybl/powsybl-core/issues/1960 and https://github.com/powsybl/powsybl-iidm4cpp/issues/421 to fix it later

File: include/powsybl/iidm/VoltageLevel.hpp [hunk 6]
```diff
@@ -207,9 +208,18 @@ class VoltageLevel : public Container {
...
+    stdcxx::CReference<T> getConnectable(const std::string& id, const stdcxx::CReference<Substation>& substation, const stdcxx::CReference<Network>& networkRef) const;
+
     virtual void removeTopology() = 0;
 
+    void setNetworkRef(Network& network);
+
+    friend class NetworkIndex;
+
 private:
+    stdcxx::Reference<Network> m_networkRef;
```
Comment (mathbagu) [inline include/powsybl/iidm/VoltageLevel.hpp:221]: Why don't we use `NetworkRef` instead like we did in Substation?

File: src/iidm/VoltageLevel.cpp [hunk 7]
```diff
@@ -262,6 +271,12 @@ VoltageLevel& VoltageLevel::setLowVoltageLimit(double lowVoltageLimit) {
     return *this;
 }
 
+void VoltageLevel::setNetworkRef(Network& network) {
+    if (static_cast<bool>(m_networkRef)) {
```
Comment (mathbagu) [inline src/iidm/VoltageLevel.cpp:275]: Why this test? m_networkRef is always set except if the VoltageLevel is detached. Then, you will never enter this method. Do I miss something?
