### PR TITLE
[IIDM v1.3] Bug MultiVariant (#165)

### LINKED ISSUE #165: [IIDM 1.3] Correction bug MultiVariant
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Multivariant voltage level's extensions are not impacted when the network's variant changes.

* **What is the expected behavior?**
They should be impacted.

* **Please tell us about your environment:**
  - PowSyBl Version: 3.5.0

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

cf powsybl/powsybl-core#1404

### PR DESCRIPTION
**Pull request by sebalaig**
**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
#165 

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Bug fix/Feature

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**
This PR fixes #165 
It also backports https://github.com/powsybl/powsybl-core/pull/682 and https://github.com/powsybl/powsybl-core/pull/1476

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

### CODE REVIEW

File: include/powsybl/iidm/Connectable.hpp [hunk 1]
```diff
@@ -22,7 +21,7 @@ namespace iidm {
 
 class Network;
 
-class Connectable : public Identifiable, public MultiVariantObject {
+class Connectable : public Identifiable {
```
Comment (mathbagu) [inline include/powsybl/iidm/Connectable.hpp:24]: This class is a merge of Connectable and AbstractConnectable. You should not remove MultiVariantObject from the inheritance tree.

**Review by mathbagu — CHANGES_REQUESTED** [review]
Do I miss something or do you misunderstand what you should do for this PR?

File: include/powsybl/iidm/Identifiable.hpp [hunk 2]
```diff
@@ -22,10 +23,19 @@ namespace iidm {
...
 
+protected:  // MultiVariantObject
+    void allocateVariantArrayElement(const std::set<unsigned long>& indexes, unsigned long sourceIndex) override;
+
+    void deleteVariantArrayElement(unsigned long index) override;
+
+    void extendVariantArraySize(unsigned long initVariantArraySize, unsigned long number, unsigned long sourceIndex) override;
+
+    void reduceVariantArraySize(unsigned long number) override;
+
```
Comment (mathbagu) [inline include/powsybl/iidm/Identifiable.hpp:38]: This block is not well placed: should be in the `protected` area

File: include/powsybl/iidm/Connectable.hpp (hunk 1 above)
Comment (mathbagu) [inline include/powsybl/iidm/Connectable.hpp:24]: Update the PR description to report that you're backporting #682

You forget to change the implementation of the MultiVariantObject methods to call the identifiable code. MultiVariant extensions of HvdcLine will not be notified by a variant change

File: include/powsybl/iidm/MultiVariantObject.hpp [hunk 3]
```diff
@@ -30,6 +31,7 @@ class MultiVariantObject {
     virtual void reduceVariantArraySize(unsigned long number) = 0;
 
 private:
+    friend class Identifiable;
```
Comment (mathbagu) [inline include/powsybl/iidm/MultiVariantObject.hpp:34]: Why do you need to make Identifiable friend of MultiVariantObject?

File: include/powsybl/iidm/HvdcLine.hpp [hunk 4]
```diff
@@ -22,7 +21,7 @@ namespace iidm {
 class HvdcConverterStation;
 class Network;
 
-class HvdcLine : public Identifiable, public MultiVariantObject {
+class HvdcLine : public Identifiable {
```
Comment (mathbagu) [inline include/powsybl/iidm/HvdcLine.hpp:24]: You forget to change the implementation of the MultiVariantObject methods to call the identifiable code. MultiVariant extensions of HvdcLine will not be notified by a variant change

File: include/powsybl/iidm/Switch.hpp [hunk 5]
```diff
@@ -21,7 +20,7 @@ namespace iidm {
 
 class VoltageLevel;
 
-class Switch : public Identifiable, public MultiVariantObject {
+class Switch : public Identifiable {
```
Comment (mathbagu) [inline include/powsybl/iidm/Switch.hpp:23]: To be checked: does the implementation of MultiVariantObject methods ok (super call?)

File: include/powsybl/iidm/VoltageLevel.hpp [hunk 6]
```diff
@@ -41,7 +40,7 @@ class Terminal;
 class VscConverterStation;
 class VscConverterStationAdder;
 
-class VoltageLevel : public Container, public MultiVariantObject {
+class VoltageLevel : public Container {
```
Comment (mathbagu) [inline include/powsybl/iidm/VoltageLevel.hpp:43]: To be checked: does the implementation of MultiVariantObject methods ok (super call?)

File: src/iidm/ConfiguredBus.hpp [hunk 7]
```diff
@@ -25,7 +24,7 @@ class BusTerminal;
 class Network;
 class Terminal;
 
-class ConfiguredBus : public Bus, public MultiVariantObject {
+class ConfiguredBus : public Bus {
```
Comment (mathbagu) [inline src/iidm/ConfiguredBus.hpp:27]: To be checked: does the implementation of MultiVariantObject methods ok (super call?)

**Review by mathbagu — CHANGES_REQUESTED** [review]

File: include/powsybl/iidm/VoltageLevel.hpp (hunk 6 above)
Comment (sebalaig) [reply include/powsybl/iidm/VoltageLevel.hpp:43]: VoltageLevel does not have any custom implementation of MultiVariantObject methods.

File: include/powsybl/iidm/MultiVariantObject.hpp (hunk 3 above)
Comment (sebalaig) [reply include/powsybl/iidm/MultiVariantObject.hpp:34]: So that MultiVariantObject protected methods can be called from their Identifiable implementation

File: include/powsybl/iidm/Identifiable.hpp (hunk 2 above)
Comment (sebalaig) [reply include/powsybl/iidm/Identifiable.hpp:38]: Ok done. (moved in its own protected section as it is a MultiVariantObject overriden methods)

File: include/powsybl/iidm/HvdcLine.hpp (hunk 4 above)
Comment (sebalaig) [reply include/powsybl/iidm/HvdcLine.hpp:24]: Ok, done by backporting Java PR #1476

File: include/powsybl/iidm/Switch.hpp (hunk 5 above)
Comment (sebalaig) [reply include/powsybl/iidm/Switch.hpp:23]: Ok, done by backporting Java PR #1476

File: src/iidm/ConfiguredBus.hpp (hunk 7 above)
Comment (sebalaig) [reply src/iidm/ConfiguredBus.hpp:27]: Ok, done by backporting Java PR #1476
